### ISSUE TITLE
Guidance for contributors?

### ISSUE THREAD

**Issue by daverosoff** [thoppe/Encyclopedia-of-Finite-Graphs#19]
Hello--I realize this might not be the right place to ask this question. I looked for other ways to get in touch but didn't find any.

An undergraduate research student and I noticed that Cartesian product is still on the list of "future invariants" on the Github site and it seemed like a good idea for me to write to you to ask whether you have already completed the classification work, and if not, whether you have advice or guidance for how she can make a useful contribution.

Thanks for your stimulating work with the encyclopedia and for any response you might give us.
-Dave

**Comment by thoppe** [comment]
Hello Dave, 

I would be happy to help you contribute to this project. The paper associated with the project is in the final stages of publication for the Discrete Journal of Mathematics, so no substantial work has been done on adding new invariants. If you would like to contribute, we can walk you through the steps needed to do so. RIght now, the project lacks a how-to guide to do, so I'll use our interaction as a template for future contributors.

Let's continue this conversation off the github issue board. Please email me at travis.hoppe at gmail.
